version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: '0'
    restart: unless-stopped
    volumes:
      - ${HOME}/server-mgr/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${HOME}/server-mgr/monitoring/prometheus_db:/var/lib/prometheus
      - ${HOME}/server-mgr/monitoring/prometheus_db:/prometheus
      - ${HOME}/server-mgr/monitoring/prometheus_db:/etc/prometheus
      - ./alert.rules:/etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/'
      - '--storage.tsdb.retention.time=240h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: '0'
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ${HOME}/server-mgr/monitoring/grafana_db:/var/lib/grafana/
    depends_on:
      - prometheus
    ports:
      - 3000:3000